swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get User Accounts
      description: Retrieve a list of user accounts with their IDs, amounts, and names
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/ResponseAccounts'
        '400':
          description: Invalid Values
        '500':
          description: Internal Server Error

  /account/{accountId}/{startDate}/{endDate}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Transactions for a specific period
      description: Retrieve transactions for an account within a specified date range
      parameters:
        - name: accountId
          in: path
          description: Account ID
          required: true
          type: string
        - name: startDate
          in: path
          description: |
            Start date of the transaction period
            (format: {MM-DD-YYYY})
          required: true
          type: string
        - name: endDate
          in: path
          description: |
            End date of the transaction period
            (format: {MM-DD-YYYY})
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/ResponseTransactionDetails'
        '400':
          description: Invalid values
        '401':
          description: Not authorized
        '500':
          description: Internal Server Error

  /{accountId}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Transaction details
      description: Get transaction details
      parameters:
        - name: accountId
          in: path
          description: Account ID
          required: true
          type: string
        - name: transactionId
          in: path
          description: Transaction ID
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/ResponseAccountsAndTransactions'
        '400':
          description: Invalid values
        '401':
          description: Not authorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

    patch:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Update Transaction's details
      description: Update transaction details
      parameters:
        - name: accountId
          in: path
          description: Account ID
          required: true
          type: string
        - name: transactionId
          in: path
          description: Transaction ID
          required: true
          type: string
        - name: Details
          in: body
          description: Update transaction's category
          required: true
          schema:
            $ref: '#/definitions/EditableDetails'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/ResponseTransactionsPatch'
        '400':
          description: Invalid values
        '401':
          description: Not authorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

  

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string

  ResponseAccounts:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        format: string
        example: User accounts successfully retrieved
      body:
        type: array
        items:
          $ref: '#/definitions/AccountInfo'

  AccountInfo:
    type: object
    properties:
      accountId:
        type: string
        description: Account ID
        example: abc123
      amount:
        type: string
        description: Account Amount
        example: "$1500.00"
      accountName:
        type: string
        description: Account Name
        example: Savings Account
        
  ResponseAccountsAndTransactions:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        format: string
        example: Account and transaction details successfully retrieved
      body:
        type: array
        items:
          $ref: '#/definitions/AccountInfoAndTransactions'
          
  ResponseTransactionsPatch:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        format: string
        example: Transaction details successfully patch
      body:
        type: array
        items:
          $ref: '#/definitions/AccountInfoAndTransactions'

  AccountInfoAndTransactions:
    type: object
    properties:
      accountId:
        type: string
        description: Identifiant du compte
        example: abc123
      amount:
        type: string
        description: Montant du compte
        example: "$1500.00"
      accountName:
        type: string
        description: Nom du compte
        example: Compte d'épargne
      transactions:
        type: array
        items:
          $ref: '#/definitions/ResponseTransactionDetails'

  

  ResponseTransactionDetails:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        format: string
        example: Transaction details successfully retrieved
      body:
        type: array
        items:
          $ref: '#/definitions/Details'

  

  Details:
    type: object
    properties:
      transactionId:
        type: string
        description: transaction ID
        example: 650d8f2402a5e529d968fe44
      type:
        type: string
        description: transaction type
        example: Electronic
      category:
        type: string
        description: transaction category
        example: Food
      notes:
        type: string
        description: transaction notes
        example: >-
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum cum aspernatur laborum...

  EditableDetails:
    type: object
    properties:
      category:
        type: string
        description: Transaction category
        enum:
          - Food
          - Clothes
          - Charges
          - Fuel
          - Supplies
          - Equipment
          - Other
      notes:
        type: string
        description: Transaction notes

  


